### PR TITLE
Integrates Orama for search

### PR DESCRIPTION
**Pull request by micheleriva**
This PR implements Orama, as discussed with @tannerlinsley.

Still a work in progress. The API keys committed are public and meant to be shared publicly across the internet 🙂

### CODE REVIEW

**Comment by tannerlinsley** [comment]
Looks like width might be a bit too wide when going responsive 
IMG_4325

**Comment by tannerlinsley** [comment]
Not a deal breaker but the button appears dark even in light mode
IMG_4326

**Comment by tannerlinsley** [comment]
IMG_4327

This might have to do with the bytes stuff but there’s a black box here

**Comment by tannerlinsley** [comment]
Getting an error: DocsCalloutBytes

**Comment by micheleriva** [comment]
@tannerlinsley I used to have this error too, but it has been fixed in 329d9ddac17f151d9ab40856cd3cf2cef9d64da6 (https://github.com/TanStack/tanstack.com/pull/205/commits/329d9ddac17f151d9ab40856cd3cf2cef9d64da6). Can you try to pull?

**Comment by micheleriva** [comment]
@tannerlinsley just fixed this!

**Pull request merged**
