### PR TITLE
feat: add table of contents for docs pages

### PR DESCRIPTION
**Pull request by Nos43ratu**
Problem: The current documentation pages, like [Router Navigation](https://tanstack.com/router/latest/docs/framework/react/guide/navigation), can be challenging to navigate due to their length and density of content.

Solution: Added a Table of Contents (ToC) to the right sidebar to enhance navigation.

Changes Made:

1. Moved the DocsLayout right sidebar to be part of the document itself.
2. Added logic to extract headings dynamically from the markup content.
3. Created a Toc component to render the extracted headings.
4. Applied the existing library color scheme to the Toc component for visual consistency
5. Added heading-level padding to the Toc to clearly represent content structure

Screenshot 2024-11-26 at 13 11 27
Screenshot 2024-11-26 at 13 11 18

### CODE REVIEW

**Review by SeanCassiere — COMMENTED** [review]
@Nos43ratu please resolve the conflicts

**Review by SeanCassiere — APPROVED** [review]
Looks good! @tannerlinsley any thoughts here?

**Comment by KevinVandy** [comment]
I'm a bit concerned that there appears to be 3 scrollbars on that 2nd image, when 2 should be the max. But otherwise, I think this would be a welcome addition.

**Comment by Nos43ratu** [comment]
> @KevinVandy it can be fixed by making content margins smaller and moving toc out from right side image image or smth like this(draft) image

or making scroll inside of the toc invisible
for example [shad ui toc](https://ui.shadcn.com/docs/components/sidebar)

**Comment by KevinVandy** [comment]
When a wide enough media query is triggered, that might be good. Otherwise probably needs to stay in one side bar on medium sized screens, and hidden on mobile

**Comment by SeanCassiere** [comment]
> @KevinVandy it can be fixed by making content margins smaller and moving toc out from right side image image or smth like this(draft) image

The draft looks better. Maybe just add a light border on the left and hide it on small screens.

**Comment by Nos43ratu** [comment]
Moved toc from right side bar to the page. Saved initial page width. Made pr thiner by removing unnecessary changes.

This version can be reverted to use initial version

@SeanCassiere @KevinVandy @tannerlinsley 


https://github.com/user-attachments/assets/50d38f59-d049-4ad7-821b-7ea274a29b0c

Screenshot 2024-11-28 at 05 18 40
Screenshot 2024-11-28 at 05 18 59
Screenshot 2024-11-28 at 05 19 05

**Comment by SeanCassiere** [comment]
On http://localhost:3000/router/latest/docs/framework/react/api/router there seems to be some content width issues.

image

**Comment by Nos43ratu** [comment]
> On http://localhost:3000/router/latest/docs/framework/react/api/router there seems to be some content width issues.
> 
> image

@SeanCassiere fixed 
Screenshot 2024-11-28 at 14 17 46

**Comment by KevinVandy** [comment]
@tannerlinsley This passes my qa from just looking at the table docs. I think it makes the docs a lot easier to navigate

image

**Review by SeanCassiere — APPROVED** [review]
These changes are great! I checked them out with the docs for Router, Query, and Form.

**Comment by tannerlinsley** [comment]
Fantastic! Approved!

**Comment by SeanCassiere** [comment]
@Nos43ratu thank you for your contribution 🎉

**Comment by Nos43ratu** [comment]
Thanks guys 🙏

**Pull request merged**
